### ISSUE TITLE
-webkit- partially works with the bounce

### ISSUE THREAD

**Issue by isabelle6** [isabelle6/dsn1676-assignment-6#1]
I had the bounce working well in Firefox. Then I added the -webkit- stuff and tried the website in chrome. The bounce happened when the button was clicked, but it won't go again if I click the button when the animation has ended. It still works in Firefox.
My guess is that it has to do with 'animationend', but I don't know how to fix it. I tried adding -webkit- to that function, but it didn't do anything.

@thomasjbradley

**Comment by thomasjbradley** [comment]
You're right about `animationend`, I forgot to mention it in class. See here:
https://github.com/algonquindesign/javascript/tree/master/effects#listening-for-animations-to-end

**Comment by isabelle6** [comment]
Thank you, it works now. Is it like adding the webkit to keyframes, where you need to have two versions (one with webkit and one without)?

**Comment by thomasjbradley** [comment]
Yeah, that's exactly it. Because the `@keyframes` has a prefix, so does the event.

**Comment by isabelle6** [comment]
Ok, thanks for your help.
